[package]
name = "swf-parser"
version = "0.4.0"
authors = ["Charles Samborski <demurgos@demurgos.net>"]
description = "SWF parser"
documentation = "https://github.com/open-flash/swf-parser"
homepage = "https://github.com/open-flash/swf-parser"
repository = "https://github.com/open-flash/swf-parser"
readme = "./README.md"
keywords = ["parser", "swf", "flash"]
license = "AGPL-3.0-or-later"
edition = "2018"

[lib]
name = "swf_parser"
path = "src/lib.rs"

[[bin]]
name = "swf-parser"
path = "src/main.rs"

[dependencies]
half = "^1.3.0"
inflate = "^0.4.5"
lazy_static = "^1.3.0"
lzma-rs = "^0.1.1"
nom = "^4.2.3"
num-traits = "^0.2.6"
regex = "^1.1.5"
serde_json = "^1.0.39"
swf-tree = "^0.6.0"
swf-fixed = "^0.1.3"

[dev-dependencies]
serde = "^1.0.90"
serde_json_v8 = "^0.0.1"
test-generator = "^0.2.2"

# [replace]
# "swf-tree:0.4.1" = { path = '../../swf-tree/rs' }
