[package]
name = "swf-parser"
version = "0.0.8"
authors = ["Charles Samborski <demurgos@demurgos.net>"]
description = "SWF parser"
documentation = "https://github.com/open-flash/swf-parser"
homepage = "https://github.com/open-flash/swf-parser"
repository = "https://github.com/open-flash/swf-parser"
readme = "./README.md"
keywords = ["parser", "swf", "flash"]
license = "AGPL-3.0-or-later"
edition = "2018"

[lib]
name = "swf_parser"
path = "src/lib.rs"

[[bin]]
name = "swf-parser"
path = "src/main.rs"

[dependencies]
inflate = "^0.4.5"
lazy_static = "^1.1.0"
lzma-rs = "^0.1.1"
nom = "^4.1.1"
num-traits = "^0.2.6"
regex = "^1.0.5"
serde = "^1.0.80"
serde_derive = "^1.0.80"
swf-tree = "^0.0.18"
swf-fixed = "^0.1.0"

[dev-dependencies]
serde_json = "^1.0.32"

# [replace]
# "swf-tree:0.0.18" = { path = '../../swf-tree/swf-tree.rs' }
