[package]
name = "swf-parser"
version = "0.8.0"
authors = ["Charles Samborski <demurgos@demurgos.net>"]
description = "SWF parser"
documentation = "https://github.com/open-flash/swf-parser"
homepage = "https://github.com/open-flash/swf-parser"
repository = "https://github.com/open-flash/swf-parser"
readme = "./README.md"
keywords = ["parser", "swf", "flash"]
license = "AGPL-3.0-or-later"
edition = "2018"

[lib]
name = "swf_parser"
path = "src/lib.rs"

[[bin]]
name = "swf-parser"
path = "src/main.rs"

[dependencies]
half = "^1.3.0"
inflate = "^0.4.5"
lazy_static = "^1.3.0"
lzma-rs = "^0.1.1"
memchr = "^2.2.0"
nom = "^5.0.0"
num-traits = "^0.2.8"
regex = "^1.1.8"
serde_json = "^1.0.40"
swf-tree = "^0.9.0"
swf-fixed = "^0.1.4"

[dev-dependencies]
serde = "^1.0.94"
serde_json_v8 = "^0.0.1"
test-generator = "^0.2.2"

# [replace]
# "swf-tree:0.8.0" = { git="https://github.com/open-flash/swf-tree.git", rev = "39d95f5f23ea13703026c2ab12475607dd2caf71" }

# When testing larger files, increasing `opt-level` provides a significant speed-up.
# [profile.test]
# opt-level = 2
